name: CMake

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  x86_64-ubuntu-debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build & Test
      run: ./scripts/ci/x86_64-ubuntu-debug.sh
  x86_64-ubuntu-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: ./scripts/ci/x86_64-ubuntu-release.sh
